### ISSUE TITLE
ThatRarityEG 所著《PluginDiary 插件开发教程》的维护问题

### ISSUE THREAD

**Issue by William-Shi** [Andy-K-Sparklight/PluginDiary#8]
伏以：尊敬的 ThatRarityEG 函丈（即 Annie-K-Sparklight）已经退出 Minecraft 社区许久，其作品 PluginDiary 插件开发教程 [https://www.mcbbs.net/thread-1163259-1-3.html](https://www.mcbbs.net/thread-1163259-1-3.html) 日渐失修。

首先，主要域名 [plgdev.xuogroup.top](plgdev.xuogroup.top) 已亡。幸有 [https://plugin-diary.pages.dev](https://plugin-diary.pages.dev) 尚存，然帖内仍以 plgdev.xuogroup.top 为“教程入口”，应当修改 MCBBS 主题帖。但 Annie 老师从未给予任何人协同编辑权限。好在尚有可能同论坛版主沟通。

其次，pages.dev 页面以本 Github 仓库 [https://github.com/Andy-K-Sparklight/PluginDiary](https://github.com/Andy-K-Sparklight/PluginDiary) 为蓝本。该仓库系个人所有，若无 Annie 老师首肯，任何人不能修改。但老师已不再使用该账号了。因此，pages.dev 页面中的内容永远不可能改变。

再次，教程内容失于更新。如去年年初，图床停止运营。原有图片全无存档，并皆丢失。我非有续麟之笔，不能接西狩之坠绪。部分图片原貌，有文字记叙，可以推敲而后重绘，我窃不自揆，曾鍼小马之文（#3）。但对于[用图片以展示原理、注释文字处](https://github.com/Andy-K-Sparklight/PluginDiary/blob/master/4-1.md?plain=1#L226)，惟能阙如，以俟君子。又如，作为“实例型教程”，在[源代码](https://github.com/Andy-K-Sparklight/PluginDiaryCode)辗转抄写至教程内时也有漏处（#6）。另外，JDK 下载网址每每更新，近日又有人称网址过时（#7）。

最后，ThatRarityEG 老师曾建立过一个 Discord 聊天服务器用于讨论插件开发，定名云“PluginDiary 插件开发交流”。然而进入该服务器的邀请链接未公开发布，而是“私信获取”，自老师注销 MCBBS 账号以后，不能再私信联系。后她又将服务器移转给我，所愧管理不力，未作宣传，该聊天服务器已经名存实亡，沉寂许久，不能实现帮扶新人的原意。

故此，我拟建立一个 GitHub 组织，另建网站发布教程页面，以便更新。

@nanmenyangde @katorly @Deer403 @yinghaoting @RawDiamondMC 

一切还需各位为教程作过贡献的道席们定夺。

**Comment by TalexDreamSoul** [comment]
支持，善之也。

論當下國內之 MC 環境，確實需有一良善教導，使初發者易習插件開發。建立 GitHub 之組織，創造一網站以發佈教導之頁面，實一善謀。

先建 GitHub 之組織，多人或共編與更新教導內容。如此，雖 Annie 老師或棄，他人可共力，保教導之及時與準確。GitHub 提供版本控制與合作功能，致成員可輕鬆共編維護教導內容。

其次，建專網站以發佈教導頁面，使學插件開發者易尋及訪教導。可用 GitHub Pages 等免費托管服務，或購域名（[pvpin.net](http://pvpin.net/)）以展專業之面貌。於易導與瀏覽之網站中，學者得依所需，有條不紊學插件開發之知識。

建 GitHub 組織與網站之後，可考以下改進教導內容：

更新無效之連結與資源：對於教導中之無效連結與資源，可尋覓替代資源以更新。如無適者，可考提供替代方案或解釋相關概念，助學者理解。

補充失之圖片與程式範例：對於失之圖片，若能忆起原貌並重繪，是為良善之補充。對於失之程式範例，可試補缺部分，或提供更詳解釋與說明，以保學者理解相關概念與原理。

更新與修復錯誤資訊：以 MC 環境變遷，或有資訊過時或錯誤者。可細察教導每部分，進行必要修復與更新，以確教導內容之準確性與可靠性。

增添新內容與範例：若有新之插件開發技術或最佳實踐，可考於教導中加入相關內容與範例，助學者跟進最新之發展與趨勢。

最後，與先前為教導作貢獻者相談，邀其加入新之 GitHub 組織，共同參與教導之維護與更新。其經驗與貢獻將對教導之品質有不可磨滅之影響。

<details>
<summary>白话文</summary>

支持，好想法。

对于现国内的 MC 环境来说，确实是需要一个更好的教程，以便新手开发者能够更轻松地学习插件开发。建立一个GitHub组织，并创建一个网站来发布教程页面是一个很好的想法。

首先，建立GitHub组织将使多位开发者能够协同编辑和更新教程内容。这样，即使Annie老师不再参与，其他人仍然可以共同努力，保持教程的及时性和准确性。GitHub提供了版本控制和合作功能，使得团队成员可以轻松地共同编辑和维护教程内容。

其次，创建一个专门的网站来发布教程页面将使学习插件开发的人更容易找到和访问教程。可以使用GitHub Pages等免费的托管服务来托管网站，或者使用自己购买的域名(pvpin.net)进行更专业的展示。通过一个易于导航和浏览的网站，学习者可以按照自己的需要，有条理地学习插件开发的知识。

在建立GitHub组织和网站之后，可以考虑以下几点来改进教程内容：

更新失效的链接和资源：针对教程中失效的链接和资源，可以尝试找到可替代的资源，并进行更新。如果无法找到合适的替代品，可以考虑在教程中提供一些备用方案或者解释相关概念，以帮助学习者理解。

补充缺失的图片和代码示例：对于缺失的图片，如果你能够回忆起原貌并进行重绘，那将是很好的补充。对于缺失的代码示例，你可以尝试补充缺失的部分，或者提供更详细的解释和说明，以确保学习者能够理解相关概念和原理。

更新和修复错误的信息：随着MC环境的变化，一些信息可能已经过时或存在错误。你可以仔细检查教程中的每一部分，并进行必要的修复和更新，以确保教程内容的准确性和可靠性。

增加新的内容和示例：如果有新的插件开发技术或者最佳实践出现，你可以考虑在教程中添加相关内容和示例，以帮助学习者跟上最新的发展和趋势。

最后，与之前为教程作出贡献的道席们进行沟通，并邀请他们加入新的GitHub组织，共同参与教程的维护和更新。他们的经验和贡献将对教程的质量起到不可磨灭的作用。


</details>

**Comment by MikanAffine** [comment]
维护的问题，建议搬运到 Gitbook，同样支持 markdown 和多人协作。

**Comment by katorly** [comment]
支持，不过之前看到forks里面有人修复和补充一些内容：https://github.com/rawdiamondmc/PluginDiary  
不知道对该仓库您有何想法

**Comment by RawDiamondMC** [comment]
支持，因为各种API随时可能被弃用，建立一个组织有利于对这个教程的持续维护。

**Comment by William-Shi** [comment]
> 维护的问题，建议搬运到 Gitbook，同样支持 markdown 和多人协作。

但是本项目中包含了一些彩蛋，比如 [AC-3-3](https://plugin-diary.pages.dev/#/AC-3-3?id=%e7%84%b6%e5%90%8e%e5%91%a2%ef%bc%9f) 的“单击开始事件还原”按钮。这类彩蛋内容不属于标准 Markdown 文本格式，是作者以一系列自创的 JavaScript 处理的。如果将本项目迁移到 Gitbook，则肯定没有 docsify 那么自由，这些彩蛋该何去何从呢？

**Comment by RawDiamondMC** [comment]
而且Gitbook在国内有被墙的情况，我这里Gitbook似乎就被DNS污染了

**Comment by RawDiamondMC** [comment]
> 支持，不过之前看到forks里面有人修复和补充一些内容：https://github.com/rawdiamondmc/PluginDiary 不知道对该仓库您有何想法

我发现这个仓库的issues作者不处理的时候就随手fork了一下，处理了一下issues（

**Comment by MikanAffine** [comment]
> > 维护的问题，建议搬运到 Gitbook，同样支持 markdown 和多人协作。
> 
> 但是本项目中包含了一些彩蛋，比如 [AC-3-3](https://plugin-diary.pages.dev/#/AC-3-3?id=%e7%84%b6%e5%90%8e%e5%91%a2%ef%bc%9f) 的“单击开始事件还原”按钮。这类彩蛋内容不属于标准 Markdown 文本格式，是作者以一系列自创的 JavaScript 处理的。如果将本项目迁移到 Gitbook，则肯定没有 docsify 那么自由，这些彩蛋该何去何从呢？

个人以为，组织成立后当改写教程以适配纯 markdown. 以及 gitbook 支持很多非标准 markdown 的功能，应当能够补足。

**Comment by katorly** [comment]
> 而且Gitbook在国内有被墙的情况，我这里Gitbook似乎就被DNS污染了

我这里也给污染了，如果没有🚀就上不去，但github就可以

**Comment by MikanAffine** [comment]
> > 而且Gitbook在国内有被墙的情况，我这里Gitbook似乎就被DNS污染了
> 
> 我这里也给污染了，如果没有🚀就上不去，但github就可以

石墨文档可能也是一个选择？也支持Markdown。至于自定义js支持，如果能够众筹到独立服务器假设docsify的话也可以考虑。

**Comment by RawDiamondMC** [comment]
> > 而且Gitbook在国内有被墙的情况，我这里Gitbook似乎就被DNS污染了
> 
> 我这里也给污染了，如果没有🚀就上不去，但github就可以

我这里没🚀github也上不去：（

**Comment by yinghaoting** [comment]
可以考虑参考<https://oi-wiki.org/>和<https://ctf-wiki.org/>，使用[mkdocs](https://www.mkdocs.org/)直接部署在GitHub Pages上；如果有可能，也可以做成类似OI-Wiki和CTF-Wiki的形式？

**Comment by MikanAffine** [comment]
> 可以考虑参考https://oi-wiki.org/和https://ctf-wiki.org/，使用[mkdocs](https://www.mkdocs.org/)直接部署在GitHub Pages上；如果有可能，也可以做成类似OI-Wiki和CTF-Wiki的形式？

这是好的，反正就一堆静态网页随便放个地方。做成OI-Wiki那种感觉不适合这个教程，因为本教程只是单对Bukkit插件开发这一个项目进行分阶段介绍，只有纵向没有横向，感觉。如果以后扩展了其他项目倒可以做成OI-Wiki那样。

**Comment by William-Shi** [comment]
> > > 而且Gitbook在国内有被墙的情况，我这里Gitbook似乎就被DNS污染了
> > 
> > 
> > 我这里也给污染了，如果没有🚀就上不去，但github就可以
> 
> 石墨文档可能也是一个选择？也支持Markdown。至于自定义js支持，如果能够众筹到独立服务器假设docsify的话也可以考虑。

PVPIN Studio 可以提供相关的服务器资源，部署这个教程，所用的域名大约是  pvpin.org 。

**Comment by William-Shi** [comment]
组织名称如何定？我拟暂定 PluginDiary，该名称可用，有更好的想法吗？

**Comment by MikanAffine** [comment]
> 组织名称如何定？我拟暂定 PluginDiary，该名称可用，有更好的想法吗？

总觉得 Diary 不像教程的名称... 不过我不参与该教程的维护，我喜好的教程格式另有。

**Comment by William-Shi** [comment]
> > 组织名称如何定？我拟暂定 PluginDiary，该名称可用，有更好的想法吗？
> 
> 总觉得 Diary 不像教程的名称... 不过我不参与该教程的维护，我喜好的教程格式另有。

那定名 PVPIN Tutorial 吗😂

**Comment by RawDiamondMC** [comment]
> > 总觉得 Diary 不像教程的名称... 不过我不参与该教程的维护，我喜好的教程格式另有。
> 
> 那定名 PVPIN Tutorial 吗😂

PluginTutorial？
PVPIN一看上去还以为是PVP😂

**Comment by katorly** [comment]
> > > 组织名称如何定？我拟暂定 PluginDiary，该名称可用，有更好的想法吗？
> > 
> > 
> > 总觉得 Diary 不像教程的名称... 不过我不参与该教程的维护，我喜好的教程格式另有。
> 
> 那定名 PVPIN Tutorial 吗😂

感觉尊重原作者好一点

**Comment by William-Shi** [comment]
> > > 总觉得 Diary 不像教程的名称... 不过我不参与该教程的维护，我喜好的教程格式另有。
> > 
> > 
> > 那定名 PVPIN Tutorial 吗😂
> 
> PluginTutorial？ PVPIN一看上去还以为是PVP😂

PVPIN 是一个零基础编程教学网站，用 Bukkit 插件来带领新人接触开发。不过该社区在 2018 年关闭了。我和 KouyouX 都曾是社区成员，故名。

**Comment by William-Shi** [comment]
TalexDreamSoul 认为组织可定名为 InTutorial ，意译作“通彻透底的了解”

**Comment by William-Shi** [comment]
要不叫 InsidePlugins ？或者我们在 PluginDiary Discord 服务器（[https://discord.gg/6gUnrW8nTn](https://discord.gg/6gUnrW8nTn)）里再讨论？

**Comment by TalexDreamSoul** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by TalexDreamSoul** [comment]
Support.

**Comment by William-Shi** [comment]
> Support.

@KouyouX @TalexDreamSoul @RawDiamondMC @Deer403 @nanmenyangde 

已邀请各位大佬加入 https://github.com/InsidePlugins

**Comment by TalexDreamSoul** [comment]
私以为此事已了，适时关闭ISSUE较好。

（实际为会出现在我的 Notifications 里面）

**Comment by William-Shi** [comment]
八月十二日下午两点，ThatRarityEG 用弃置许久的 GitHub 账号给我们的仓库点了个 Star（参见 [plugin-diary-docs/stargazers](https://github.com/InsidePlugins/plugin-diary-docs/stargazers) ），足见我们已经取得了一定成果。既然补订工作可以有序开展，本 Issue 就暂先关闭。
